-- A15 ejercicio 9
SELECT FIRST_NAME ||', '|| JOB_ID AS "EMPLOYEE AND TITLE"  
FROM EMPLOYEES;

SELECT FIRST_NAME ||', '|| JOB_ID  "EMPLOYEE AND TITLE"  
FROM EMPLOYEES;

--EJERCICIO 10
SELECT EMPLOYEE_ID
       || ',' || FIRST_NAME
       || ',' || LAST_NAME
       || ',' || EMAIL
       || ',' || PHONE_NUMBER
       || ',' || HIRE_DATE
       || ',' || SALARY THE_OUTPUT
FROM EMPLOYEES;
--PAG A-21
--EJERCICIO 9 

SELECT FIRST_NAME
      ,SALARY
      ,COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT > 0
ORDER BY SALARY DESC,COMMISSION_PCT DESC;

SELECT FIRST_NAME
      ,SALARY
      ,COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT > 0
ORDER BY 2 DESC,3 DESC;

-- EJERCICIO 10
SELECT FIRST_NAME
      ,SALARY
FROM EMPLOYEES
WHERE SALARY>&INGRESE_SALARIO;

-- PAG A-31
-- EJERCICIO 9
SELECT LAST_NAME
      ,ROUND((SYSDATE - HIRE_DATE)/7,0) AS TENURE
FROM EMPLOYEES
ORDER BY TENURE DESC;

--PAG A 37
-- EJERCICIO 5
SELECT JOB_ID
      , DECODE(JOB_ID, 'AD_PRES','A'
                      ,'ST_MAN','B'
                      ,'IT_PROG','C'
                      ,'SA_REP','D'
                      ,'ST_CLERK','E'
                      ,'0') GRADO
FROM EMPLOYEES;

-- PAG A-43
-- EJER 9
SELECT MANAGER_ID
      ,MIN(SALARY) MINIMO
FROM EMPLOYEES
WHERE MANAGER_ID > 0
      AND SALARY > 6000
GROUP BY MANAGER_ID
ORDER BY MINIMO DESC;





