DELIMITER //
CREATE TRIGGER NUEVA_VENTA AFTER INSERT ON VENTAS
    FOR EACH ROW
    BEGIN
        UPDATE CLIENTE SET ID_ULTIMO_PEDIDO = NEW.ID_ARTICULO 
        WHERE ID=NEW.ID_CLIENTE;
        UPDATE ALMACEN SET STOCK=STOCK - NEW.CANTIDAD 
        WHERE ID_ARTICULO=NEW.ID_ARTICULO;  
    END
//
DELIMITER ;

INSERT INTO ventas
     (id_articulo,id_cliente,cantidad,precio)
     VALUES
     (300,1,10,125);

-- CREAR UN TRIGGER PARA ELIMINAR UN USUARIO
-- BORRAR TODAS SUS COMVERSACIONES
-- BORRAR DE LOS GRUPOS
-- BORRAR SUS PUBLICACIONES O ANUNCIOS

-- http://manuales.guebs.com/mysql-5.0/error-handling.html

DELIMITER //
CREATE TRIGGER NUEVO_CLIENTE BEFORE INSERT ON CLIENTE
    FOR EACH ROW
    BEGIN
        IF NEW.NOMBRE='' THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: EL NOMBRE NO PUEDE ESTAR VACIO';
        END IF;
    END;
//
DELIMITER ;

INSERT INTO CLIENTE(NOMBRE) VALUES ('');

DELIMITER //


DELIMITER //
CREATE TRIGGER VALIDAR_VENTA BEFORE INSERT ON VENTAS
    FOR EACH ROW
    BEGIN
        #SELECT STOCK FROM ALMACEN WHERE ID_ARTICULO=new.ID_ARTICULO; 
        IF (SELECT STOCK FROM ALMACEN WHERE ID_ARTICULO=new.ID_ARTICULO) < new.CANTIDAD THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: nO EXISTE LA CANTIDAD PEDIDA EN EL ALMACEN';
        END IF;
    END
//
DELIMITER ;

INSERT INTO ventas
     (id_articulo,id_cliente,cantidad,precio)
     VALUES
     (300,1,25,225);